name: Dawn

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      
      - name: Run tests
        run: |
          pytest

      - name: run pylint
        if: ${{success()}}
        run: |
          echo "linting with pylint..."
          pylint . --ignore=venv, .pytest_cache



